---
url: http://ci.moneydesktop.com
poll_interval: 300
projects:
  - 9-morannon-master
  - 6-ballista-master
  - 3-abacus-master
  - 1-amigo-master
  - 2-amigo-stable
  - 15-persona-master
  - 13-peon-master
  - 11-newman-master
  - 12-newman-stable
  - 10-morannon-stable
  - 7-ballista-stable
  - 4-abacus-stable
  - 18-toolbox-stable
  - 16-persona-stable
  - 14-peon-stable
